spring.application.name=demo
server.port=9090

# Database configuration
#spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/admin?authSource=admin
# Format: mongodb://username:password@host:port/database?authSource=authenticationDatabase
spring.data.mongodb.uri=mongodb://mymongo:27017/test

# Logging Configuration
logging.level.root=INFO
logging.level.com.demo=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/application.log

